### ISSUE TITLE
file_end sometimes wrong

### ISSUE THREAD

**Issue by dentalfloss1** [lwa-project/orville_wideband_imager#20]
On some archival oims files, the file_end date is well after the file should have ended. As the screenshot below shows, it appears that on these files, we are getting confused about the units used in "int_len"
![image](https://github.com/lwa-project/orville_wideband_imager/assets/24629883/5fc99e7e-e9eb-4455-874d-bf9bbf5f8137)

**Comment by jaycedowell** [comment]
I see this in the `lwana` branch at https://github.com/lwa-project/orville_wideband_imager/blob/lwana/orville_imager.py#L1236.

Is this a North Arm-only issue or is it also affecting Sevilleta?

**Comment by dentalfloss1** [comment]
It looks like it currently is not affecting Sevilleta because we are now storing int_len in days at Sevilleta:
[cid:3ac02599-7f5d-4159-8b06-e8ded94f4814]
________________________________

**Comment by jaycedowell** [comment]
Great, I've deployed the fix for North Arm.
