### ISSUE TITLE
Make pip installable

### ISSUE THREAD

**Issue by dentalfloss1** [lwa-project/orville_wideband_imager#21]
Now that this repository has grown to include a few scripts, the lack of ability to do a "pip install" on it is a bit cumbersome. In order to make this repository pip installable, it would require writing a setup.py file or other equivalent file along with moving files around into subdirectories.

**Comment by jaycedowell** [comment]
Done but we need to pull the relevant changes into the lwana branch.

**Comment by jaycedowell** [comment]
I guess that works for lwana.  The tests passed.
